a = (str(input()))
print('['+str(int(a[0])*int(10000))+']')
print('['+str(int(a[1])*int(1000))+']')
print('['+str(int(a[2])*int(100))+']')
print('['+str(int(a[3])*int(10))+']')
print('['+str(int(a[4])*int(1))+']')